### ISSUE TITLE
ERROR: LoadError: ArgumentError: Package FEMBasis does not have Tensors in its dependencies:

### ISSUE THREAD

**Issue by OVGULIU** [JuliaFEM/FEMBase.jl#66]
Hello,

I cannot test FEMBase:
`
ERROR: LoadError: ArgumentError: Package FEMBasis does not have Tensors in its dependencies:`

Also 
[compat]
julia = "≥ 1.0"
Calculus = "0.5"
Tensors = "1"

not works...

**Comment by ahojukka5** [comment]
This is already fixed, and waiting for the next release. https://github.com/JuliaRegistries/General/pull/5967. Meanwhile, you can checkout the earlier FEMBasis release.

**Comment by ahojukka5** [comment]
This however probably has nothing to do with https://github.com/JuliaFEM/UMAT.jl/issues/19.
